# action.yml
name: 'balena-ci'
description: 'Automate release build and deployments'
inputs:
  balena_token:
    description: 'Your balenaCloud API token'
    required: true
  fleet:
    description: 'Name of the fleet you want to build the release for'
    required: true
  environment:
    description: 'Domain for the backend services to build your release'
    required: false
    default: 'balena-cloud.com'
  versionbot:
    description: 'Does the repository use Versionbot ?'
    required: false
    default: false
  target:
    description: 'Name of branch where code is considered merged'
    required: false
    default: 'master'
  finalize:
    description: 'Should the action finalize a release after building'
    required: false
    default: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    BALENA_TOKEN: ${{ inputs.balena_token }}
    BALENA_URL: ${{ inputs.environment }}
