name: Unit Tests 

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  nodeJS:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 12.x
        uses: actions/setup-node@v2
        with:
          node-version: 12.x
      - name: Test preperation
        run: sed -i '/"balena-cli":/d' package.json
      - name: Install dependencies
        run: npm ci
      - run: npm test
